### ISSUE TITLE
The `setup_requires` are not searched in cache

### ISSUE THREAD

**Issue by calind** [pex-tool/pex#17]
I'm trying to build a pex archive and I have all the package dependencies local but it looks like `setup_requires` are not checked in cache, but rather installed from pypi.

I'm trying to build a pex with pygit2 like this: `pex -v --no-pypi --cache-dir=/tmp/build/packages/ -r 'pygit2'`, but I'm getting this error. The build machine has no internet connection:

```
pex.http: Crawling /tmp/build/packages/: 0.5ms
**** Failed to install pygit2-0.21.3. stdout:OKgW2

**** Failed to install pygit2-0.21.3. stderr:
Download error on https://pypi.python.org/simple/cffi/: [Errno 111] Connection refused -- Some packages may not be found!
Couldn't find index page for 'cffi' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 111] Connection refused -- Some packages may not be found!
No local packages or download links found for cffi
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "setup.py", line 215, in <module>
    cmdclass=cmdclass)
  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
    replace_conflicting=True
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 610, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi')

pex: Packaging pygit2: 88.0ms
pex:   Installing /tmp/tmp7OKgW2: 86.8ms
Traceback (most recent call last):
  File "/usr/bin/pex", line 9, in <module>
    load_entry_point('pex==0.7.0', 'console_scripts', 'pex')()
  File "/usr/lib/python2.7/dist-packages/pex/bin/pex.py", line 310, in main
    pex_builder = build_pex(args, options)
  File "/usr/lib/python2.7/dist-packages/pex/bin/pex.py", line 277, in build_pex
    platform=options.platform)
  File "/usr/lib/python2.7/dist-packages/pex/resolver.py", line 101, in resolve
    raise Unsatisfiable('Cannot satisfy requirements: %s' % requirement_set[requirement.key])
pex.resolver.Unsatisfiable: Cannot satisfy requirements: [Requirement.parse('pygit2==0.21.3')]
```

The contents of `/tmp/build/packages/` is:

```
/tmp/build/packages/cffi-0.8.6.tar.gz
/tmp/build/packages/pycparser-2.10.tar.gz
/tmp/build/packages/pygit2-0.21.3.tar.gz
```

**Comment by jsirois** [comment]
Ok, going back in the time machine with this `Dockerfile`:
```dockerfile
FROM ubuntu:14.04

RUN apt-get update && \
    apt-get install -y \
        python-virtualenv \
        cmake \
        build-essential \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        curl \
        git \
        libncursesw5-dev \
        xz-utils \
        tk-dev \
        libxml2-dev \
        libxmlsec1-dev \
        libffi-dev \
        liblzma-dev

ENV WORKDIR=/pex/issues/17
WORKDIR $WORKDIR

RUN git clone https://github.com/libgit2/libgit2 && \
    cd libgit2 && \
    git reset --hard v0.21.3 && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
    cmake --build . --target install

ENV LD_LIBRARY_PATH=/usr/local/lib
ENV LIBGIT2=/usr/local

RUN git clone https://github.com/pyenv/pyenv && \
    cd pyenv && \
    src/configure && \
    make -C src

ENV PYENV_ROOT="$WORKDIR/pyenv"
ENV PATH="$PYENV_ROOT/bin:$PATH"

RUN pyenv install 2.7.18 && \
    pyenv global 2.7.18

RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc

RUN curl -fLO https://curl.se/ca/cacert.pem && \
    virtualenv -p "$PYENV_ROOT/versions/2.7.18/bin/python2.7" .venv && \
    .venv/bin/pip --cert cacert.pem install -U "pip==20.3.4" && \
    .venv/bin/pip install -U setuptools wheel pex

RUN echo 'source $WORKDIR/.venv/bin/activate' >> ~/.bashrc

CMD ["/bin/bash", "-i"]
```

I find modern Pex works for your use case @calind. The only change is to use `--find-links` instead of `--cache-dir` and that modern Pex no longer needs `-r`, you just list the requirements as positional args:
```console
# Build the way back machine:
:; docker build -t issues-17 .
[+] Building 0.0s (13/13) FINISHED                                                                                                                                                      docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                              0.0s
 => => transferring dockerfile: 1.31kB                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:14.04                                                                                                                                   0.0s
 => [1/9] FROM docker.io/library/ubuntu:14.04                                                                                                                                                     0.0s
 => CACHED [2/9] RUN apt-get update &&     apt-get install -y         python-virtualenv         cmake  build-essential  libssl-dev  zlib1g-dev  libbz2-dev  libreadline-dev  libsqlite3-dev  cur  0.0s
 => CACHED [3/9] WORKDIR /pex/issues/17                                                                                                                                                           0.0s
 => CACHED [4/9] RUN git clone https://github.com/libgit2/libgit2 &&     cd libgit2 &&     git reset --hard v0.21.3 &&     mkdir build &&     cd build &&     cmake .. -DCMAKE_INSTALL_PREFIX=/u  0.0s
 => CACHED [5/9] RUN git clone https://github.com/pyenv/pyenv &&     cd pyenv &&     src/configure &&     make -C src                                                                             0.0s
 => CACHED [6/9] RUN pyenv install 2.7.18 &&     pyenv global 2.7.18                                                                                                                              0.0s
 => CACHED [7/9] RUN echo 'eval "$(pyenv init -)"' >> ~/.bashrc                                                                                                                                   0.0s
 => CACHED [8/9] RUN curl -fLO https://curl.se/ca/cacert.pem &&     virtualenv -p "/pex/issues/17/pyenv/versions/2.7.18/bin/python2.7" .venv &&     .venv/bin/pip --cert cacert.pem install -U "  0.0s
 => CACHED [9/9] RUN echo 'source $WORKDIR/.venv/bin/activate' >> ~/.bashrc                                                                                                                       0.0s
 => exporting to image                                                                                                                                                                            0.0s
 => => exporting layers                                                                                                                                                                           0.0s
 => => writing image sha256:185cbc26f0335734afb4781d883bb9fbb446136b8eac9e5c41fa12ba63d52db5                                                                                                      0.0s
 => => naming to docker.io/library/issues-17

# Use it to test out modern Pex on this old setup:
:; docker run --rm -it issues-17
(.venv)root@eec0a01c04f3:/pex/issues/17# pip --no-python-version-warning -q download -d /tmp/build/packages/ --no-binary :all: pygit2==0.21.3
(.venv)root@eec0a01c04f3:/pex/issues/17# pip --no-python-version-warning -q download -d /tmp/build/packages/ wheel
(.venv)root@eec0a01c04f3:/pex/issues/17# ls -1 /tmp/build/packages/
cffi-1.15.1.tar.gz
pycparser-2.21.tar.gz
pygit2-0.21.3.tar.gz
wheel-0.37.1-py2.py3-none-any.whl
(.venv)root@eec0a01c04f3:/pex/issues/17# pex -V
2.16.2
(.venv)root@eec0a01c04f3:/pex/issues/17# pex --no-pypi --find-links /tmp/build/packages/ pygit2
Pex 2.16.2 ephemeral hermetic environment with 1 requirement and 3 activated distributions.
Python 2.7.18 (default, Aug 23 2024, 03:23:59)
[GCC 4.8.4] on linux2
Type "help", "pex", "copyright", "credits" or "license" for more information.
>>> pex()
Running from ephemeral loose PEX directory: /tmp/tmpBbXSdi
Requirements:
  pygit2
Activated Distributions:
  pygit2-0.21.3-cp27-cp27mu-linux_x86_64.whl
  cffi-1.15.1-cp27-cp27mu-linux_x86_64.whl
  pycparser-2.21-py2.py3-none-any.whl
>>> import pygit2
/root/.cache/pex/installed_wheels/af43fa63ac776b21d0c8ceb091e58910529a4b79bfbc14b0850e844cef382d5c/cffi-1.15.1-cp27-cp27mu-linux_x86_64.whl/cffi/model.py:537: UserWarning: 'git_checkout_notify_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
>>> pygit2.__file__
'/root/.cache/pex/installed_wheels/fa752bed5fe70f92d18b842225a92ad01367cad9b18acb898f28e6acaaff1904/pygit2-0.21.3-cp27-cp27mu-linux_x86_64.whl/pygit2/__init__.py'
>>>
(.venv)root@eec0a01c04f3:/pex/issues/17# exit
```

So, @calind I'm going to close this as (finally) fixed somewhere along the way in the last 10 years.
