### ISSUE TITLE
zipfile.BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by sholsapp** [pex-tool/pex#177]
Hi everyone,

We periodically see the following error in an environment in which pex files are periodically (somewhat frequently) rotated on disk as the version increases and we do a new release. My suspicion is that we see this error when we rotate the pex file while it is executing or unpacking.

Have others seen this and give me a tip on i) root cause and ii) how to safely prevent?

Thanks! :+1: 

```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "__main__.py", line 25, in <module>
  File ".bootstrap/_pex/pex_bootstrapper.py", line 99, in bootstrap_pex
  File ".bootstrap/_pex/pex.py", line 55, in __init__
  File ".bootstrap/_pex/pex_info.py", line 76, in from_pex
  File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File ".bootstrap/_pex/common.py", line 76, in open_zip
  File "/usr/lib64/python2.6/zipfile.py", line 696, in __init__
    self._GetContents()
  File "/usr/lib64/python2.6/zipfile.py", line 716, in _GetContents
    self._RealGetContents()
  File "/usr/lib64/python2.6/zipfile.py", line 728, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by kwlzn** [comment]
@sholsapp this would make sense if the pex file is being truncated while being executed (e.g. a slow network copy process writes the first 1/5th of the file at the moment that pex is trying to unzip it).

how are you "rotating" the pex file exactly (i.e. what command/setup)?

have you considered the ol' create-then-atomically-rename ("echo blah > $FILE.tmp && mv $FILE.tmp $FILE" trick?

**Comment by jsirois** [comment]
@sholsapp, Kris asked some good questions that were never answered. These would need answers to provide further help. I'm going to close this as an answered question, but please re-open if you are still struggling with this and have more details you can provide.
