### ISSUE TITLE
unhandled AttributeError during pex bootstrapping 

### ISSUE THREAD

**Issue by kwlzn** [pex-tool/pex#63]
looks like bootstrapping might be broken in the current version of pex:

```
>>> from pex import pex_bootstrapper
>>> pex_bootstrapper.bootstrap_pex_env('/home/kwilson/test_flask_wsgi.pex')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/kwilson/.pex/install/pex-0.8.4-py2.py3-none-any.whl.92fa056b8fc3f5f9ade278207ae2d42306515ec8/pex-0.8.4-py2.py3-none-any.whl/pex/pex_bootstrapper.py", line 80, in bootstrap_pex_env
    PEXEnvironment(entry_point, PexInfo.from_pex(entry_point)).activate()
  File "/home/kwilson/.pex/install/pex-0.8.4-py2.py3-none-any.whl.92fa056b8fc3f5f9ade278207ae2d42306515ec8/pex-0.8.4-py2.py3-none-any.whl/pex/environment.py", line 134, in activate
    self._working_set = self._activate()
  File "/home/kwilson/.pex/install/pex-0.8.4-py2.py3-none-any.whl.92fa056b8fc3f5f9ade278207ae2d42306515ec8/pex-0.8.4-py2.py3-none-any.whl/pex/environment.py", line 140, in _activate
    self.update_candidate_distributions(self.load_internal_cache(self._pex, self._pex_info))
  File "/home/kwilson/.pex/install/pex-0.8.4-py2.py3-none-any.whl.92fa056b8fc3f5f9ade278207ae2d42306515ec8/pex-0.8.4-py2.py3-none-any.whl/pex/environment.py", line 124, in update_candidate_distributions
    if self.can_add(dist):
  File "/home/kwilson/.pex/install/pex-0.8.4-py2.py3-none-any.whl.92fa056b8fc3f5f9ade278207ae2d42306515ec8/pex-0.8.4-py2.py3-none-any.whl/pex/environment.py", line 129, in can_add
    return distribution_compatible(dist, self._interpreter, self.platform)
  File "/home/kwilson/.pex/install/pex-0.8.4-py2.py3-none-any.whl.92fa056b8fc3f5f9ade278207ae2d42306515ec8/pex-0.8.4-py2.py3-none-any.whl/pex/package.py", line 247, in distribution_compatible
    package = Package.from_href(dist.location)
AttributeError: 'NoneType' object has no attribute 'location'
```

**Comment by kwlzn** [comment]
does appear that bootstrapping from a pristine environment works tho (prior example was running inside of an existing pex via PEX_MODULE='' ./pex):

```
>>> import os, sys
>>> entry_point = '/home/kwilson/test_flask_wsgi.pex'
>>> sys.path.insert(0, entry_point)
>>> sys.path.insert(0, os.path.join(entry_point, '.bootstrap'))
>>>
>>> from _pex import pex_bootstrapper
>>> pex_bootstrapper.bootstrap_pex_env(entry_point)
>>>
```

**Comment by jsirois** [comment]
This bug is in the bespoke resolver code that was replaced with Pip in the 2.x version bump; so I'll close this as no longer applying / fixed by the 2.x series.
