### ISSUE TITLE
re.error on bootstrap

### ISSUE THREAD

**Issue by neskk** [pex-tool/pex#705]
There seems to be an error on `third_party\__init__.py` that prevents PEX files from running on Windows.

I've been trying to generate a PEX for enjarify and it has been a nightmare.

```
D:\Workspace\Python\enjarify>py -3 enjarify.pex
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "enjarify.pex\__main__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Workspace\Python\enjarify\enjarify.pex\.bootstrap\pex\third_party\__init__.py", line 430, in <module>
  File "D:\Workspace\Python\enjarify\enjarify.pex\.bootstrap\pex\third_party\__init__.py", line 407, in install
  File "D:\Workspace\Python\enjarify\enjarify.pex\.bootstrap\pex\third_party\__init__.py", line 205, in install_vendored
  File "D:\Workspace\Python\enjarify\enjarify.pex\.bootstrap\pex\third_party\__init__.py", line 255, in install
  File "D:\Workspace\Python\enjarify\enjarify.pex\.bootstrap\pex\third_party\__init__.py", line 153, in _iter_importables
  File "D:\Workspace\Python\enjarify\enjarify.pex\.bootstrap\pex\third_party\__init__.py", line 108, in iter_root_modules
  File "D:\Workspace\Python\enjarify\enjarify.pex\.bootstrap\pex\third_party\__init__.py", line 119, in _filter_names
  File "C:\Python37\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Python37\lib\sre_parse.py", line 507, in _parse
    code = _escape(source, this, state)
  File "C:\Python37\lib\sre_parse.py", line 402, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \p at position 11
```

On linux (WSL) it runs properly but has an older python version (3.5.3) vs windows (3.7).
I don't know if it's about the difference in versions, but even generating the PEX file in windows results in the same outcome.

Just run a test with pex 1.5.3 and it worked flawlessly, generated PEX file with python 3.7 in Windows, runs on Windows and also on WSL (debian) with python 3.5

**Comment by yorinasub17** [comment]
I believe https://github.com/pantsbuild/pex/pull/638 addressed this.

**Comment by jsirois** [comment]
I agree, #638 appears to have been the fix here. That said - Pex has never claimed to support Windows and still does not.
